### ISSUE TITLE
Appveyor Build Failing

### ISSUE THREAD

**Issue by Arithmos-Health** [biolab/orange3-installers#17]
Appveyor build is failing when I fork and run. 

```reg delete HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics /f || cd .
The operation completed successfully.
reg delete HKEY_CURRENT_USER\Software\Python\ContinuumAnalytics /f || cd .
ERROR: The system was unable to find the specified registry key or value.
dir orange3\dist
 Volume in drive C has no label.
 Volume Serial Number is 0CA6-1C58

**Comment by ales-erjavec** [comment]
Can you post the full output?

**Comment by Arithmos-Health** [comment]
(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1 
(%PREFIX%) %SRC_DIR%>call "%SRC_DIR%\run_test.bat" 
(%PREFIX%) %SRC_DIR%>orange-canvas --help 
Usage: orange-canvas [options] [workflow_file]
Options:
  -h, --help            show this help message and exit
  --no-discovery        Don't run widget discovery (use full cache instead)
  --force-discovery     Force full widget discovery (invalidate cache)
  --clear-widget-settings
                        Remove stored widget setting
  --no-welcome          Don't show welcome dialog.
  --no-splash           Don't show splash screen.
  -l LOG_LEVEL, --log-level=LOG_LEVEL
                        Logging level (0, 1, 2, 3, 4)
  --style=STYLE         QStyle to use
  --stylesheet=STYLESHEET
                        Application level CSS style sheet to use
  --qt=QT               Additional arguments for QApplication
(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit /B 1 
(%PREFIX%) %SRC_DIR%>python -c "import pkg_resources as pr; pr.require('Orange3')" 
(%PREFIX%) %SRC_DIR%>IF 1 NEQ 0 exit /B 1 
(%PREFIX%) %SRC_DIR%>IF 1 NEQ 0 exit 1 
TESTS FAILED: orange3-3.29.0.dev0+63ed27f-py38ha925a31_0.tar.bz2
if "%CONDA%" == "" ( ..\ci\appveyor-build.bat )
for %%s in ( dist/Orange3*.exe ) do ( set "INSTALLER=%%s" )
echo INSTALLER = %INSTALLER%
INSTALLER = 
set "PATH=%PATH_BEFORE_BUILD%"
cd ..
mkdir installers
reg delete HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics /f || cd .
The operation completed successfully.
reg delete HKEY_CURRENT_USER\Software\Python\ContinuumAnalytics /f || cd .
ERROR: The system was unable to find the specified registry key or value.
dir orange3\dist
 Volume in drive C has no label.
 Volume Serial Number is 0CA6-1C58
 Directory of C:\projects\orange3-installers\orange3
File Not Found
Command exited with code 1

**Comment by ales-erjavec** [comment]
Please update to current master and try again.

**Comment by Arithmos-Health** [comment]
Thank you. It now works.
